[package]
name = "dendryform-html"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Responsive HTML renderer for dendryform diagrams"
keywords.workspace = true
categories.workspace = true

[dependencies]
dendryform-core.workspace = true
dendryform-layout.workspace = true
thiserror.workspace = true

[dev-dependencies]
dendryform-parse.workspace = true
serde_json.workspace = true
